name: Feature Request
body:
  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Explain your use case
  - type: textarea
    id: proposal
    attributes:
      label: Desired solution
      description: What would solve your use case?
